Dev 836/drop ins guide
Dwolla/dev-portal pull request #307
Opened 2022-02-15 21:28 UTC by ShreyaThapa

2022-03-01 02:23 UTC, spencerhunter requested changes

2022-03-01 02:23 UTC, spencerhunter commented on pages/guides/drop-ins/generate-client-token.mdx
> +## Token URL vs Token
Update to `Token URL vs Token Configuration`

2022-03-01 02:23 UTC, spencerhunter commented on pages/guides/drop-ins/generate-client-token.mdx
> +The drop-in components have multiple isolated functions connected together into a single user flow. Throughout the flow of a component, the dwolla-web library will make multiple http calls to an endp
- Should we say "A majority of drop-in components" instead of "The drop-in components"? Using the makes it sound like all, which I'm not sure is true. 
- Uppercase HTTP

2022-03-01 02:23 UTC, spencerhunter commented on pages/guides/drop-ins/generate-client-token.mdx
> +There are two to configure your drop-ins components for fetching client-tokens -
We can probably remove the links for navigation here since what we're describing is in the next subsection and there are links in the "on this page" nav that they can use to jump to the respective section.

2022-03-01 02:23 UTC, spencerhunter commented on pages/guides/drop-ins/generate-client-token.mdx
> +There are two to configure your drop-ins components for fetching client-tokens -
Maybe just say, "In the following sections we'll outline the difference between the two options available in dwolla-web.js for retrieving client-tokens; using either the `tokenUrl` or `token` configuration."

2022-03-01 02:23 UTC, spencerhunter commented on pages/guides/drop-ins/generate-client-token.mdx
> +Create a server-side `tokenUrl` endpoint that can be called by the dwolla-web library when an action needs to be performed within the flow. This is necessary and allows for fetching client-tokens as
Made some small tweaks to this paragraph. Suggested edits below:

Using the `tokenUrl` option when configuring dwolla-web.js requires creating a server-side endpoint that can be called by the library when an action needs to be performed within a flow component. Establishing an endpoint enables the ability for the component to fetch client-tokens on-demand in order to render the appropriate UI. The server-side endpoint should act as a pass-through by taking in the request body required in order to make the appropriate call to the /client-tokens endpoint. Upon success, the /client-tokens endpoint will return response body including a "token" string value. The HTTP response that is returned to the client-side is expecting an object in the format of `{token: 'Token string value'}`. More information on configuration of dwolla-web.js can be found in [step 3](https://developers.dwolla.com/guides/drop-ins/using-drop-in-components#configure-dwolla-webjs) of this guide.

2022-03-01 02:23 UTC, spencerhunter commented on pages/guides/drop-ins/generate-client-token.mdx
> +Create a function that calls your server-side `tokenUrl` endpoint and returns a promise containing a token. Then set up the configuration of the drop-in with a `token` parameter which calls that func
Smol suggested edits:

Using the `token` option when configuring the dwolla-web.js library allows you to create a function that calls your server-side `tokenUrl` endpoint (As described above). The function you create takes in two arguments, 1) the request body that is required to make the /client-tokens API request; and 2) a JSON object the includes key:value pairs for specifying custom headers. When an action needs to be performed within a flow component, the dwolla-web.js library will call your custom function and dynamically pass in a request body as the first argument. The server-side endpoint should act as a pass-through by taking in the request body required in order to make the appropriate call to the /client-tokens endpoint. Upon success, the /client-tokens endpoint will return response body including a "token" string value. The HTTP response that is returned to the client-side is expecting an object in the format of `{token: 'Token string value'}`.

2022-03-02 15:03 UTC, ShreyaThapa commented
Thanks for the review and suggestions, @spencerhunter. Changes and comments are addressed in this [commit](https://github.com/Dwolla/dev-portal/pull/307/commits/f364809eeabd7edd8110e38edcbe2b040e7c8205). This is ready for final review!

2022-03-02 15:42 UTC, spencerhunter approved these changes

2022-03-02 17:23 UTC, merged