Dev 1446
Dwolla/dev-portal pull request #544
Opened 2023-09-22 21:38 UTC by ShreyaThapa

2023-09-26 20:00 UTC, spencerhunter commented on pages/api-reference/connect/authorization/index.mdx
> +Dwolla utilizes the [OAuth 2 protocol](https://oauth.net/2/) to facilitate authorization. OAuth is an authorization framework that enables a third-party application to obtain access to protected reso
Edit: Replace `Customers` with External Parties

2023-09-26 20:03 UTC, spencerhunter commented on pages/api-reference/connect/authorization/index.mdx
> +#### Creating an application
Let's plan on removing this section for now

2023-09-26 20:07 UTC, spencerhunter commented on pages/api-reference/connect/root/index.mdx
> +The "root" serves as an entry point to the API, providing your application with the ability to fetch and discover resources available based on the OAuth `access_token` provided in the request. If an
Remove parenthesis at end of paragraph.
```suggestion
The "root" serves as an entry point to the API, providing your application with the ability to fetch and discover resources available based on the OAuth `access_token` provided in the request. If an application access token is provided in the request, the API will return links to resources that belong to the Dwolla application.
```

2023-09-26 20:07 UTC, spencerhunter commented on pages/api-reference/connect/root/index.mdx
> +{
Updated example to include just the account link
```suggestion
{
    "_links": {
        "account": {
            "href": "https://api-sandbox.dwolla.com/accounts/d4a0876f-642e-478b-b684-bfb8632c5937",
            "type": "application/vnd.dwolla.v1.hal+json",
            "resource-type": "account"
        }
    }
}
```

2023-09-26 20:17 UTC, spencerhunter commented on assets/api-resource-tables/accounts/CreateFundingSource.tsx
> +      "required",
Can we change the required value from required to yes or no?
```suggestion
      "yes",
```

2023-09-26 20:49 UTC, spencerhunter commented on pages/api-reference/connect/transfers/initiate.mdx
> +## Request and response - using `ach`
Let's remove `- using ach` for now until we have more transfer types to demonstrate in the docs

2023-09-26 20:50 UTC, spencerhunter commented on pages/api-reference/connect/webhooks/index.mdx
> +When a new event is created, and there is an active [webhook subscription](/api-reference/connect/webhook-subscriptions), a new webhook is created in order to deliver that event. Attempted deliveries
Let's remove this link for now
```suggestion
We recommend that applications protect against duplicated events by [making event processing idempotent](/guides/webhooks/process-validate#check-for-duplicate-events).
```

2023-09-26 20:53 UTC, spencerhunter commented on pages/api-reference/connect/webhook-subscriptions/list-webhooks.mdx
> +title: List Webhooks
should we change this to `List webhooks for a webhook subscription`?

2023-09-26 20:54 UTC, spencerhunter requested changes
@ShreyaThapa Added a few comments! Overall, it looks good. Update endpoint titles to be sentence case and it should be g2g

2023-09-26 21:55 UTC, ShreyaThapa commented
Addressed comments and accepted suggestions!

2023-09-28 13:21 UTC, spencerhunter approved these changes

2023-09-28 14:30 UTC, merged